### ISSUE TITLE
Rework Gruntfile to pull docs/examples from the video.js dist, not from video.js doc

### ISSUE THREAD

**Issue by OwenEdwards** [videojs/docs#27]
The Gruntfile needs reworking to bring the docs/example files from the dist/docs directory of video.js (where they are designed to be part of the distribution); they depend on the built and dist-ready JavaScript and CSS files in that directory structure, and are not designed to work "out of the box" in the video.js doc directory.

Personally, I think the changes in [video.js #2915](https://github.com/videojs/video.js/pull/2915) were a mistake - although they got the simple-example working on the docs.videojs.com site, they tie that example to an old version of video.js (5.0.2?!), whereas the fix should have happened in the build process here, so that index.html files work here on the doc site _and_ in the dist, and refer to the version of video.js that they were with when they were built.

**Comment by rcrooks** [comment]
This is correct - however, since the doc build process has been split off from the video.js build process, I don't know how to get the distribution. @gkatsev can you think about this? I think the best solution is to pull the doc generation back into the video.js build process.

**Comment by gkatsev** [comment]
This is no longer valid. All docs are generated in video.js now and published based on the `docs/api` from the published video.js
