### ISSUE TITLE
Sound off option

### ISSUE THREAD

**Issue by giocodes** [videojs/docs#28]
Would be great to have a sound off option.

Looked at the docs and GitHub without any luck. 

✌️

**Comment by mboles** [comment]
Although for Brightcove Player, in this case will be the same for Video.js: http://docs.brightcove.com/en/video-cloud/brightcove-player/guides/volume-control.html

-Matt

**Comment by gkatsev** [comment]
Yup, you probably wanted [`muted()`](http://docs.videojs.com/docs/api/player.html#Methodsmuted).
You can either call `muted()` on the player, or supply it as an html attribute on the video element:

``` html
<video muted controls class="video-js"></video>
```

Hope that helps. (Thanks @mboles!)

**Comment by giocodes** [comment]
Thanks!
