### ISSUE TITLE
All links in docs' index page are broken

### ISSUE THREAD

**Issue by varemenos** [videojs/docs#30]
All the links from http://docs.videojs.com/index.html are broken, they are supposed to link in the guides section but instead the 404.

For example, the FAQ link is supposed to point towards `/tutorial-faq.html` but instead it points towards  `/guides/faq.md`

**Comment by brandonocasey** [comment]
There is currently a [PR against video.js](https://github.com/videojs/video.js/pull/4200) that should fix most of the links in the docs.

**Comment by gkatsev** [comment]
This has been fixed, thanks for reporting @varemenos.
