### ISSUE TITLE
Code not rendered correctly in player example

### ISSUE THREAD

**Issue by nikolas** [videojs/docs#6]
At the top of this page: http://docs.videojs.com/docs/api/player.html

The code isn't escaped properly. It looks like:

<hr>

 In the following example, the data-setup attribute tells the Video.js library to create a player instance when the library is ready.

```
&lt;video id=&quot;example_video_1&quot; data-setup='{}' controls>
  &lt;source src=&quot;my-source.mp4&quot; type=&quot;video/mp4&quot;>
&lt;/video>
```

**Comment by rcrooks** [comment]
working on a fix.....

**Comment by rcrooks** [comment]
fixed
